### ISSUE TITLE
Broken links on PyPI

### ISSUE THREAD

**Issue by briandefiant** [wordfence/wordfence-cli#114]
All of the links from `README.md` on the [PyPI page for WF CLI](https://pypi.org/project/wordfence/) are broken. May be related to #23.

**Comment by davidnuzik** [comment]
Note: To be tested later, and upon release of v2.1.0 (so that PyPi release happens and updates https://pypi.org/project/wordfence/ with the fix)

**Comment by davidnuzik** [comment]
v2.1.0-rc2 11/27/23 (https://test.pypi.org/project/wordfence/2.1.0rc2/ website)

**SUMMARY:**
QA validation PASSED. Testing was done via a test PyPi release and by checking https://test.pypi.org/project/wordfence/2.1.0rc2/

**VALIDATION STEPS**
1. Navigate to https://test.pypi.org/project/wordfence/2.1.0rc2/
2. Compare to the non-test site, https://pypi.org/project/wordfence/ 
3. Notice that on the test.pypi.org site, all the broken links now work as expected. No issues observed.
