### ISSUE TITLE
Restrict users from being able to set workers to 0 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#115]
Currently a user can set the number of workers to 0, which appears to run the malware-scan infinitely with 0% CPU usage.

**Comment by davidnuzik** [comment]
As of `4ddb7b0` (11/20/23) I can specify zero workers during non-interactive configure like:
`wordfence configure --request-license --accept-terms --cache-directory=/home/david/.cache/wordfence --workers=0`
And when cat the config under [MALWARE_SCAN] I see workers = 0

**Comment by akenion** [comment]
@davidnuzik The config prompt should not accept `0` as an option for the number of workers. I'll get that corrected.

As for manually configuring, when running `malware-scan` now with no workers, you should get the following message:
```
Error: Scans require at least one worker
```

Let me know if you're not seeing that, but otherwise I think that piece is OK.

**Comment by davidnuzik** [comment]
> Let me know if you're not seeing that, but otherwise I think that piece is OK.
Yes I see that and am not able to scan - this piece of logic is fine.

**Comment by davidnuzik** [comment]
v2.1.0-rc2 11/27/23

**SUMMARY:**
QA validation PASSED. I can no longer supply zero workers either with interactive `configure` process or via non-interactive means.

**VALIDATION STEPS**
1. Try to manually `configure` wordfence and supply zero workers. This is no longer allowed and now output is shown when attempting to enter zero mentioning "Please enter a value that is at least 1" and the user is re-prompted to enter the worker count.
Upon supplying an integer the correct supplied integer is still saved properly to the wordfence-cli.ini file, as expected.
2. Attempt to do the same but in a non-interactive fashion by leveraging the new args in v2.1.0 that permit automated means of configuring. For example with the following:
`wordfence configure --request-license --accept-terms -D --workers=0 -o`
As expected, the logic works here as well again mentioning "Please enter a value that is at least 1" and the process exits with exit code 1 which makes sense. Check the wordfence-cli.ini file and as expected it is not altered / written to. Test again supplying 1 or greater int and the process still works as expected, updating the wordfence-cli.ini file properly.
