### ISSUE TITLE
Update wording for the configure subcommand prompt when a INI file already exists

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#116]
Currently, when running the `configure` subcommand with an existing configuration file, the user is prompted with: 

> An existing configuration file was found at /home/esther/.config/wordfence/wordfence-cli.ini, do you want to overwrite it? [y/n] (default: n): 

Since the original settings can be retained rather than completely reset, it might be more clear to the user to say change "overwrite" to "update", or something along those lines: 
> An existing configuration file was found at /home/esther/.config/wordfence/wordfence-cli.ini, do you want to update it? [y/n] (default: n):

**Comment by davidnuzik** [comment]
Built at `4ddb7b0` 11/20/2023 _Testing prior to release of an RC is very low risk in this area and related issues involving configure can catch any issues, should they arise with an RC._

**SUMMARY:**
QA validation PASSED.

**VALIDATION STEPS**
- Have an existing wordfence-cli.ini in the default location.
- Run `wordfence configure` the language now reads as follows ("overwrite" is now "update")
`An existing configuration file was found at /home/david/.config/wordfence/wordfence-cli.ini, do you want to update it? [y/n] (default: n):`
