### ISSUE TITLE
Using option --read-stdin, the scan subcommands do not complete and user is forced to interrupt. 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#118]
When explicitly using `--read-stdin` option for both malware-scan and vuln-scan, the scan does not complete as expected.

**Vuln-scan**
Ex. `wordfence vuln-scan /www/wordpress --read-stdin` 
Compare to behavior where read-stdin is the default such as with command ex. `wordfence vuln-scan /www/wordpress`. When explicitly using `--read-stdin` option, the scan does not resolve and instead forces the user to interrupt and ending in `^CError: `

**Malware-scan**
Ex. `wordfence malware-scan /www/wordpress --read-stdin` 
Compare to behavior where read-stdin is the default such as with command ex. `wordfence malware-scan /www/wordpress`. In this case it appears the scan freezes before completing when explicitly using `--read-stdin`. The user has to force an interrupt to end the scan.

**Comment by akenion** [comment]
This is not an issue. `--read-stdin` is the default behavior, when stdin is not a TTY, just to clarify. The scan will terminate once it processes the end of the input from stdin. The appropriate way to complete the scan when using `--read-stdin` with input from a terminal in this case is trigger EOF (end-of-file) on stdin. This can be done using `Ctrl` + `D`. This is behaving as expected.
