### ISSUE TITLE
Updates to wording for various --help options

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#121]
Update the wording for --help options to the following: 

**both malware-scan & vuln-scan**
- --read-stdin: Remove "Specify --no-read-stdin to disable." for redundancy
- --output: Remove "Use --no-output to disable." for redundancy
- --output-headers: Change first line to "Include column headers on output"
- --cache: Change to "Enable cache. Cache is enabled by default."

**vuln-scan**
-  -I, --informational: Change to: "Includes informational vulnerability records in results. Defaults to disabled."
-  -M, --relative-mu-plugins-path: Change to "Alternate path of the wp-content/mu-plugins directory relative to the WordPress root"

**help**
_displays same options for `wordfence` `wordfence configure --help` and `wordfence version --help`_
- --cache: Change to "Enable cache. Cache is enabled by default."

**Comment by davidnuzik** [comment]
`4bbd7b0` 11/20/23 _Testing with my own local build just prior to rc rather than WITH the RC as this is extremely low risk. I'm getting a head start on testing for this case since it's very unlikely something changes in any significant way that affects/breaks help in this area for malware-scan._

**SUMMARY:**
QA validation PASSED.

**VALIDATION STEPS**
- Run `wordfence malware-scan --help` and observe the changes:
     - `--read-stdin` now does not include "Specify --no-read-stdin to disable." which was previously at the end of the first line.
     - `--output` now does not include "Use --no-output to disable." which was previously at the end of the first line.
     - `--output-headers` now reads "Include column headers on output" which previously read "Whether or not to include column headers in output."
     - `--cache` now reads "Enable caching. Caching is enabled by default." which previously read "Whether or not to enable the cache."
          - Check each of `wordfence`, `wordfence configure --help`, and `wordfence version --help` as the issue suggested. They are all the same and look good.
          - Technically, this wording is not per the criteria in the issue but I like it better -- it reads better in my opinion and makes sense.
- Run `wordfence vuln-scan --help` and observe the changes:
     - `-I, --informational` now reads "Includes informational vulnerability records in results.". Previously it read "Whether or not to include informational vulnerability records in results."
          - Technically, the criteria indicates to also include "Defaults to disabled." but we don't do this for other flags that are not enabled by default. I think this is fine.
     - `-M, --relative-mu-plugins-path` Now reads "Alternate path of the wp-content/mu-plugins directory relative to the WordPress root" Previously the "mu-" was missing at "[...]wp-content/plugins[...]"
- Test again but by invoking `help` in different ways i.e. wordfence help, wordfence <subcommand> -h, and --help - all should be the same. (I also have some test automation for this step and will check prior to release).

**NOTES:**
```
      --read-stdin             Read paths from stdin. If not specified, paths will automatically be read from stdin when input is not from a TTY.
                               (use --no-read-stdin to disable)
```

```
      --output                 Write results to stdout. This is the default behavior when --output-path is not specified.
                               (use --no-output to disable)
```

```
      --output-headers         Include column headers in output.
                               Compatible formats: csv, tsv, null-delimited, line-delimited
                               (use --no-output-headers to disable)
```

```
      --cache                  Enable caching. Caching is enabled by default.
                               (use --no-cache to disable)
```

```
  -I, --informational             Include informational vulnerability records in results.
                                  (use --no-informational to disable)
```

```
  -M, --relative-mu-plugins-path  Alternate path of the wp-content/mu-plugins directory relative to the WordPress root.
```
