### ISSUE TITLE
Preserve comments in existing INI files when configure command is invoked

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#123]
Currently any custom comments added to the wordfence-cli.ini file are overwritten when a `wordfence configure` command is invoked. Add the ability to preserve comments in the INI files. May want to consider prompting the user if they want to preserve the comments in the event the comments are no longer relevant with the new configuration.

**Comment by akenion** [comment]
We are using Python's built-in `configparser` library to read/write INI files at present. It does not support preserving comments. We'll need to switch to another library in order to implement this change.
