### ISSUE TITLE
Validate license key when using -l --license with vuln-scan subcommand

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#124]
Validate license key input when using `-l --license` with `vuln-scan` subcommand. No change needed for malware-scan subcommand license key validation.

**Comment by davidnuzik** [comment]
> Built locally at `4ddb7b0` 11/20/23

A traceback is shown if the license is not valid. Not a big deal -- the error message is shown but kind of a nit that we see a traceback / invalid license is not handled nicely.

```
wordfence vuln-scan -l <free license with 1 character changed so is invalid> .

[logo removed from output]

Traceback (most recent call last):
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/cli/licensing.py", line 44, in validate_license
    if not client.ping_api_key():
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/api/noc1.py", line 112, in ping_api_key
    return self.process_simple_request('ping_api_key')
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/api/noc1.py", line 57, in process_simple_request
    self.validate_response(response, validator)
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/api/noc1.py", line 43, in validate_response
    raise ApiException(
wordfence.api.exceptions.ApiException: Error message received in response body: WordFence API error: The Wordfence key you're using is not in a valid format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/.local/bin/wordfence", line 8, in <module>
    sys.exit(main())
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/cli/cli.py", line 199, in main
    exit_code = cli.invoke()
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/cli/cli.py", line 181, in invoke
    license_manager.check_license()
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/cli/licensing.py", line 71, in check_license
    self.validate_license(current)
  File "/home/david/.local/lib/python3.9/site-packages/wordfence/cli/licensing.py", line 52, in validate_license
    raise LicenseValidationFailure(
wordfence.cli.licensing.LicenseValidationFailure: Invalid license: WordFence API error: The Wordfence key you're using is not in a valid format.
```

**Comment by davidnuzik** [comment]
I created https://github.com/wordfence/wordfence-cli/issues/153 to track the traceback(s) when an invalid license key is supplied.

**Comment by davidnuzik** [comment]
v2.1.0-rc1 (built with pip) 11/22/23

**SUMMARY:**
QA validation PASSED.
I can now see requests made to wordfence.com when I invoke `vuln-scan` and pass a valid `-l` license key. When I compare to v2.0.3 I do not see any requests go thru.

**VALIDATION STEPS**
1. Set up wireshark or other means of capturing packets (tcpdump, etc).
2. Filter for IPs we use for API calls.
3. With v2.1.0-rc1, execute a vuln-scan like `wordfence vuln-scan <path> -l <license_key>` and I observe API requests made to check the license.
4. Test again but with v2.0.3 and I do not see these requests.

**Comment by davidnuzik** [comment]
v2.1.0-rc2 (built with pip) 11/22/23

**SUMMARY:**
QA validation PASSED.
_**This was tested again because the traceback I mentioend prior in this issue is being handled in this case. As such a re-testing of this case was executed here -- this time with rc2**_

**VALIDATION STEPS**
1. Execute the validation steps from my prior comment -- ensure license validation still works as expected (it does.)
2. Now, test again, but this time supply and INVALID license key -- in my case one which has just on character changed.

_The result is wordfence cli now handles this gracefully -- a traceback is no longer shown._
Now I just see the expected message, and once:
`Error: Invalid license: WordFence API error: The Wordfence key you're using is not in a valid format.`
