### ISSUE TITLE
Improvements to logging - prefix loglevel per message ("DEBUG: ", etc) and/or add `--log-level` argument

### ISSUE THREAD

**Issue by davidnuzik** [wordfence/wordfence-cli#129]
**Summary:**
I propose we consider one or more of the following for at least each `vuln-scan` and `malware-scan` sub-commands:
- Add "DEBUG: " as a prefix for any debug log level messages - this can help to differentiate between -v verbose level and -d debug level
- Perhaps add a `--log-level` argument as an option with options such as error, warn, info, verbose, debug, etc or whatever is applicable for the logging configuration / library we utilize.
- Optionally, expand on logging messages where sensible such as:
-- `vuln-scan` providing more DEBUG output -- perhaps list each file checked when set -d flag or otherwise more verbosity when specify -d or -v (currently not much useful output when set either flag for vuln-scan unlike malware-scan currently.
-- `malware-scan` perhaps providing -d flag results in more verbose output more than -v currently (for each file scanned, if malware detected output section of file and sig detected as well?)

-----

**Use Case:**
I, a power user / dev / QA / engineer, would like to be able to differintiate between debug messages and verbose messages when I pass -d and -v. 
Ideally, I would like specificity for the log level I am looking for for my output whether it be on the tty or for my file output. This way I may specify `--log-level=debug` in order to troubleshoot something during my automation / cron job / tty session / etc.

**Additional Info and Remarks:**
I suggest for "standard" output (i.e. no -d debug or -v verbose arg, or if we add it no --log-level arg supplied) we do NOT output prefixes like "INFO: " so that default/standard output looks cleaner and more attractive by default.

**Comment by akenion** [comment]
I've added a `--prefix-log-levels` option that enables prefixes for all log levels, including debug. This is now the default behavior _when colored output is disabled_.

Additionally, I've added a `--log-level`/`-L` option that allows explicitly specifying the minimum log level. Only messages at or above that level will be included in output.

I don't see a need for additional debug output at this point, but if there's a specific use-case, we can certainly add it.

**Comment by davidnuzik** [comment]
Sounds good to me. Thanks!

**Comment by davidnuzik** [comment]
v2.1.0-rc1 (built using pip) 11/22/23

**SUMMARY:**
QA validation PASSED.
I was able to pass `-L` or `--log-level` and test with most levels -- I was able to create output using vuln-scan that shows INFO, WARNING, and DEBUG messages and also was able to cause an error. When I changed the log-level the output was filtered as expected (i.e. DEBUG shows all the way up to DEBUG level, INFO shows up to INFO level but no DEBUG, etc. Additionally `--prefix-log-levels` works as expected.

**VALIDATION STEPS**
1. Execute a `vuln-scan` on a malware sample "hacked" site (has signatures to trigger results). Test repeatidly with various log levels.
2. Test but with `--prefix-log-levels` set.
3. Test but with invalid path to cause an error.
4. Test but use an invalid log level such as "TACOS" - cli outputs help information and indicates that "TACOS" are not a valid log level [regardless of how delicious they are].
```usage: wordfence <SUBCOMMAND> [OPTIONS]
vuln-scan: error: argument --log-level/-L: invalid choice: 'TACOS' (choose from 'DEBUG', 'VERBOSE', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
```

**NOTES:**
No issues observed during testing. I couldn't test every single type of log level, but based on my testing of several I am confident everything is working fine and as expected.

I did notice that when I pass an invalid dir to vuln-scan an "Error" message is shown but even with CRITICAL set it is still shown. _I believe this makes sense -- in this case I NEED to see this error message regardless so I know I passed an invalid path._ Additionally, I don't think that message is part of logging -- rather it's normal output ("Error" isn't in all CAPS unlike the log levels). Just mentioning this for informative purposes -- no concerns here.

**Comment by davidnuzik** [comment]
Reopened due to bug identified with rc2 after testing done last week (my last comment on this issue).

I seem to have missed a bug (unless the issue did not happen in rc1, but this is unlikely) where when the log level is set to VERBOSE or lower level, output during a `malware-scan` has a prefix like `Level 15:`, whereas `VERBOSE:` was expected.

**Comment by davidnuzik** [comment]
v2.1.0-rc3 (amd64 binary) 11/29/23

**SUMMARY:**
QA validation PASSED.
I can confirm the latest PR resolves the issue where malware-scan output would show verbose logging as prefix `Level 15` it now shows as expected (`VERBOSE:`)

**VALIDATION STEPS**
- Run any malware-scan with VERBOSE or lower level log-level -- the prefix now reads `VERBOSE:` instead of `Level 15:`.

**NOTES:**
I smoke tested log levels again and prefix log levels option. No issues. More in-depth testing was already done prior [here](https://github.com/wordfence/wordfence-cli/issues/129#issuecomment-1823438773).
