### ISSUE TITLE
Add Scanned Path as an output column for --output-columns

### ISSUE THREAD

**Issue by scottbisker** [wordfence/wordfence-cli#130]
When scanning multiple WP installations, having the `scanned_path` available as an output column would improve the usability of the the output file for reporting and future actions.

**Comment by davidnuzik** [comment]
v2.1.0-rc1 (built with pip) 11/22/23

**SUMMARY:**
QA validation PASSED.
There is now a new option for the `vuln-scan` subcommand for the `--output-columns` arg, and its `scanned_path` if you specify this and do a non-human output (csv, tsv, etc) the full path is now shown -- making interrupting results much easier for multiple WP installs. (Note that full path is shown by default for results with `human` output and as such `scanned_path` doesn't have any affect for this output format).

**VALIDATION STEPS**
1. Execute a vuln-scan and designate csv output and --output-columns `scanned_path` at a root directory with more than one wordpress install. Also, including `--output-headers` so we can also determine the header displays as expected. For example, `wordfence vuln-scan ~/malware-samples --output-path /home/david/myOutputForAllInstalls.csv --output-columns scanned_path --output-headers -m csv`
2. Inspect the CSV output. It shows the `scanned_path` column I designated and paths for my results. We can see its shown for both of my example sites "demoHackedSite" and "demoHackedSite2"
```
scanned_path
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite2/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
/home/david/malware-samples/demoHackedSite/
```

**NOTES:**
Note, regarding step 1 the result is the same if you specify scan paths explicitly for example `~/malware-samples/demoHackedSite/ ~/malware-samples/demoHackedSite2/` -- there is just new logic now that you can designate a parent folder (in this case "malware-samples") and all detected WP installations within it automatically get scanned. This was not the case with our prior releases.

Further testing with 2.1.0 will be done with regards to output, the various output args, etc -- resolution of this issue does not mean full validation of all output with 2.1.0 has been completed yet, rather just this area.

Note that `malware-scan` has `filename` as a column option which will also display path and filename for results for the malware-scan subcommand. This is not a part of validating this issue but is mentioned here for reference.
