### ISSUE TITLE
Malware-scan is not displaying verbose output on Mac environment

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#161]
Running `malware-scan` on the latest rc2 on a Mac Ventura is not displaying verbose output either as default behavior or with specifying `-v` / `--verbose`. Also not displaying with the `--debug` option. This was also confirmed not displaying in `--progress` mode. 

Found while testing case #132.

**Comment by akenion** [comment]
The last fix prevented verbose output from being shown in the progress output on Mac.

**Comment by ewodrich** [comment]
Verified --verbose now displays as the default in both --progress mode and TTY. Also confirmed this is working on linux vm as well. This including verifying the following: 

- no-verbose
- debug
- no-debug
- quiet
- no-quiet
- various -L log levels
- prefix-log-levels
