### ISSUE TITLE
Valid args placed in wordfence-cli.ini file result in "Ignoring unknown config setting" message even though they work

### ISSUE THREAD

**Issue by davidnuzik** [wordfence/wordfence-cli#184]
**Summary:**
If you add a valid arg to the ini such as "exclude_signatures" with one or more valid values (signature Ids) it will work -- my malware scans will indeed skip the one or more sig ids I supplied. However, the CLI will mention the following (even though the arg works and is valid)
`Ignoring unknown config setting "exclude_signatures"`
`*** Invalid settings not known to wordfence-cli or that are not intended for use in INI config files were discarded. ***`
Adding additional entries in the INI file causes similar errors, even though they work. I noticed messages can be repeated too:
`Ignoring unknown config setting "exclude_signatures"`
`Ignoring setting that is not valid in the config file context: "prefix-log-levels".`
`Ignoring setting that is not valid in the config file context: "prefix-log-levels".`
`*** Invalid settings not known to wordfence-cli or that are not intended for use in INI config files were discarded. ***`

-----

**Environment:**
Ubuntu 22.04.03, amd64
v2.1.0rc5 (latest RC as of 12/4/23)

**Steps to Reproduce:**
1. Configure `wordfence` if not already done. The default config file is written to ~/.config/wordfence/wordfence-cli.ini
2. Edit the .ini file -- in the [DEFAULT] section of the ini, and just below existing entries (typically "cache_directory") add a valid argument, such as the following example: `exclude_signatures = 8426,10657,5408,13564`. Save the file.
3. Now, run a `malware-scan` -- in my case the path I supply contains the signatures I am excluding. I indeed do NOT get results returned since `exclude_signatures` values are excluded. Other results I have with other sigs are detected, as expected.  In short, the setting in the INI file took and works regardless of the error messages.
4. Last, and optionally, edit the INI again and add below `exclude_signatures` the setting: `prefix_log_levels = yes`. Now scan again - log levels are prefixed now, however We see the message twice that the prefix-log-levels setting is not valid.
 
**Expected Result:**
I expected no error messages presented above the Wordfence CLI logo around my valid INI settings.

**Actual Result:**
I get error messages about unknown or invalid settings in my INI file even though those settings should be valid and actually do work.

**Additional Info:**
I tested --exclude-signatures prior to editing my .ini file and had the same, expected/working, behavior -- my four sig ids were skipped on the CLI. When I place it in the INI and do NOT include --exclude-signatures on the CLI they are still skipped (in other words this setting in the INI file actually took, regardless of the two lines of errors/messages output to the user on the tty).

Here is what my INI file looks like during testing:
```
[DEFAULT]
license = 9051<REDACTED>8191
cache_directory = ~/.cache/wordfence
noc1_url = https://<REDACTED>/
exclude_signatures = 8426,10657,5408,13564
prefix_log_levels = yes

[MALWARE_SCAN]
workers = 8

```

**Comment by akenion** [comment]
The error messages are the correct and intended behavior. There was a bug where config options that were not valid for their containing sections were still passed through and this caused the observed behavior. This should work correctly now (the error messages should be displayed when options are used improperly and such options should have no effect.

**Comment by davidnuzik** [comment]
v2.1.0rc6 12/6/23

**SUMMARY:**
QA validation PASSED.
I can confirm this issue is now resolved. 
1. First there was a misunderstanding -- args that are not global (unlike `banner` for example) need to be in the appropriate INI section.
2. Second this change fixes the problem where args placed in [DEFAULT] ini section still were passed even if they were not "global", that is to say they were args for vuln-scan or malware-scan
3. When I test various args, such as `exclude_signatures` or `output_path` by placing them in the CORRECT ini sections now they do work as expected (no error shown in tty output)
4. When I place various invalid / non-global/default args in the [DEFAULT] ini section the error remains but now it also does NOT pass those args (which is good since they are not valid in that section anyway).

**VALIDATION STEPS:**
1. Configure wordfence if not already done. Add an invalid arg to the [DEFAULT] section such as `exclude_signatures = 8426,10657,5408,13564` used prior when reporting the issue. Now, run a malware-scan and notice that this arg is NOT passed (i.e. these sigs still are used and indeed not excluded); a message is also shown indicating the setting is not valid, just as before. This is GOOD and correct behavior now.
2. Now, move the `exclude_signatures` line into the [MALWARE_SCAN] section and run a malware scan again just like before. Now the arg IS passed and it DOES work and no error is shown. This is GOOD and correct behavior now. 
3. Smoke test a few args including also with [VULN_SCAN] (typically you need to manually create this section in the INI) for example with `output_path` in VULN_SCAN. This too works as expected - smoke testing a few args applicable to specific subcommands vuln-scan and malware-scan both work. Global "banner" arg still works in any section.

**NOTES:**
For example, while smoke testing I tried some of these:

**malware-scan (`[MALWARE_SCAN]`)**
output_path = <path/file.extension>
exclude_signatures = <sigs>
banner = <true/false/yes/no> (banner is "global" and can go in any INI section)

**vuln-scan (`[VULN_SCAN]`)**
output_path = <path/file.extension>
exclude_vulnerability - <vulns>
banner = <true/false/yes/no> (banner is "global" and can go in any INI section)

**`[DEFAULT]`**
banner = <true/false/yes/no> (banner is "global" and can go in any INI section)
