### ISSUE TITLE
Build RPM package

### ISSUE THREAD

**Issue by briandefiant** [wordfence/wordfence-cli#197]
For an upcoming release, we should provide RPM packages for RHEL-based Linux distributions.

**Comment by davidnuzik** [comment]
v3.0.1rc4
RHEL 9 with subscription

**SUMMARY:**
QA validation PASSED. The RPM looks good as do the docs currently in milestone/ghost-rider branch as of 1/12/24.

**VALIDATION STEPS**
1. Enable the CRB repo as per the new RPM install docs.
2. Use DNF to install the RPM.
3. Smoke test the wordfence CLI - terms, configure, malware-scan, vuln-scan, and remediate all function as expected.

**NOTES:**
Other distros such as Fedora, Alma Linux, etc not tested. Alma Linux 9 should work.
I am going to hold on marking the issue as `qa-passed` (label) for now and smoke test with rc5 (and any other possible future RCs prior to release) once I smoke test those and feel good I'll mark this as qa-passed.

**Comment by davidnuzik** [comment]
Signing off on the RPM - smoke tested rc7 and it looks good as well. This is likely our last RC.
