### ISSUE TITLE
Clarify error message in the event a scan does not complete due to IO error

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#226]
If a vuln-scan or malware-scan fail due to IO error, update the error message to make clear the scan has failed. This is especially pertinent if a scan begins to populate output and then fails, which may be unclear to a user that the scan did not complete. 

Ideas for wording:
`Scan failed. Error: Unable to scan directory at <directory>`
`Scan could not complete. Error: Unable to scan directory at <directory>`
`Scan stopped before completing. Error: Unable to scan directory at <directory>`

Example end results with `--no-allow-io-errors` and a file that fails due to permissions:
```
Processing file: /Users/Esthe/Sites/wordpress/random-test.php
/Users/Esthe/Sites/wordpress/eicar-test-file.php,5972,Safe:DOS/EICAR-Test-File.5972,Safe test file used to confirm anti-virus detection,b'X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'
Error: Directory search of /Users/Esthe/Sites/wordpress/wp-test-permissions failed ([Errno 13] Permission denied: '/Users/Esthe/Sites/wordpress/wp-test-permissions')
```

**Comment by davidnuzik** [comment]
Question: Does running with the `-d` / `--debug` flag reveal more info? (Or do we want to reveal more info without this flag?)

**Comment by akenion** [comment]
@ewodrich Just to clarify, the option is `--no-allow-io-errors` (with two leading hyphens). It looks like you may be testing with `-no-allow-io-errors` (one hypen), which isn't supported.

**Comment by ewodrich** [comment]
Corrected scan options and updated comments as per above from akenion.

**Comment by davidnuzik** [comment]
Discussed and typically users will be technical and probably check exit codes, etc closing
