### ISSUE TITLE
Broken link on readme

### ISSUE THREAD

**Issue by Blake-** [wordfence/wordfence-cli#24]
"We have a number of installation methods to install Wordfence CLI in our [installation documentation](https://github.com/wordfence/wordfence-cli/blob/main/wordfence/wordfence-cli/blob/main/docs/Installation.md) which we'd"
Should be 
"We have a number of installation methods to install Wordfence CLI in our [installation documentation](https://github.com/wordfence/wordfence-cli/blob/main/docs/Installation.md) which we'd"

**Comment by pesc** [comment]
#23

**Comment by akenion** [comment]
These links have been corrected on the `main` branch.
