### ISSUE TITLE
optimising wordfence CLI Scan Time

### ISSUE THREAD

**Issue by sadhnamahale** [wordfence/wordfence-cli#310]
Hi Team,

I have installed the Wordfence CLI on our Ubuntu server and ran the following command:

wordfence malware-scan /var/www

However, the scan took over 3-4 hours to complete. Could you suggest any methods or configurations to speed up the scanning process?

Looking forward to your recommendations.

Thanks.

**Comment by akenion** [comment]
@sadhnamahale There are a few things you can do to improve the scan times via configuration options for Wordfence CLI.

1. Use multiple workers to scan concurrently (if the system has additional CPU cores available) - You can do this using the `--workers`/`-w` option on the command line followed by a number of workers. Be aware that each worker will consume all available CPU resources for one core, so if there are other processes (like a web server) running on the same host, you'll want to be careful not to allocate all cores to the scan. For example, to run with 4 workers, you can use the following command:
```
wordfence malware-scan -w 4 /var/www
```
2. Use the `vectorscan` match engine. This is a more efficient regex engine and will speed up the scan dramatically. This will require the `libhyperscan5` (or `libvectorscan5`) package to be installed (on Ubuntu). You can use the `wordfence version` command to check whether or not Vectorscan is detected by CLI. It will output something like this:
```
Wordfence CLI 5.0.1
PCRE Supported: Yes - PCRE Version: 8.39 2016-06-14 (JIT Supported: Yes)
Vectorscan Supported: Yes - Version: 5.2.1 2020-03-23 (API Version: 5.2.1)
```
Once vectorscan is installed, you can use the `--match-engine` flag when scanning to enable it, for example:
```
wordfence malware-scan --match-engine vectorscan /var/www
```

I'd recommend using Vectorscan along with multiple workers (depending on how many CPUs are available). Combining the two would look something like this:
```
wordfence malware-scan --match-engine vectorscan -w 4 /var/www
```

That should decrease the scan times dramatically. Let me know how this works for you and if you have any questions.

**Comment by sadhnamahale** [comment]
Hi @akenion,

Thank you for providing the best solution. It has significantly reduced scan times!

I noticed one issue, though. When I run a scan via the Wordfence UI, it identifies unknown files. However, when using the CLI, I don't get the same results. Here's the command I used:

wordfence malware-scan --output-columns filename -m null-delimited /var/www

Could you confirm if this is the correct command to detect unknown files? Or is there a different approach I should try?

Screenshot for reference

<img width="410" alt="image" src="https://github.com/user-attachments/assets/8e640329-71a3-458d-8fc5-9ea03686e53e">

Thanks.

**Comment by akenion** [comment]
I went ahead and opened #311 as a feature request for unknown file detection and tagged you there @sadhnamahale. The team will review and if it's something we decide to implement, we'll get it scheduled for an upcoming release. You can follow that issue to stay updated on the progress.

**Comment by akenion** [comment]
The user's scan time issue was resolved and the follow-up request has been moved to a new issue.
