### ISSUE TITLE
When progress output is enabled, fatal errors are not shown long enough to be read

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#37]
Messages from fatal errors are written to the progress interface which is then immediately terminated (due to the fatal error). This prevents users from being able to read these messages.

Instead, the progress interface should be terminated first and then the message should be written directly to stdout rather than through curses.

**Comment by dallasmyers** [comment]
Verified when fatal errors are triggered while in the curses interface, the interface is terminated first and the error message is written directly to stdout.

- checked running a scan using --progress with fatal errors and verify the interface is terminated and the fatal error is printed to stdout
- checked running a scan using --progress without fatal errors and verify it runs and completes as expected
- checked running a scan without using --progress with fatal errors and verify the fatal error is printed to stdout as expected
- checked running a scan without using --progress without fatal errors and verify it runs and completes as expected
- check that redirected output still logs as expected
- checked running a scan with `--allow-io-errors` and verify the previous fatal errors are no longer fatal and do not terminate the scan
