### ISSUE TITLE
Show cursor at end of scan when running with progress output to highlight completion

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#38]
Display a blinking cursor at the end of the `Scan completed! Press any key to exit.` line to indicate that the scan is complete and the user may provide input.

**Comment by ewodrich** [comment]
Tested in conjunction with #42 and verified the cursor is present and blinking in a variety of scenarios and linux environments. Note that when ssh'ing into a server using a Mac terminal window, the default Terminal setting may have the "Blink cursor" option disabled in which case the cursor appears solid at the end of the line:
`Scan completed! Press any key to exit.`
