### ISSUE TITLE
Print final scan result line to stdout after curses interface is closed

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#39]
Print the final status line, such as:
```
Found 7 matching file(s) after processing 5758 file(s) containing 97970550 byte(s) over 320 second(s)
```

After the user closes the curses interface so that information is not lost.

**Comment by dallasmyers** [comment]
Verified the final scan result line is now printed to stdout after the curses interface is closed.

- the final status line is printed within the curses interface upon scan completion and then to stdout after the curses interface is closed
- scanning without --progress continues to produce expected results
- checked with various amount of matching files found, total files, bytes, and seconds
- additionally checked with other options included
