### ISSUE TITLE
Gracefully handle terminal resizing with progress output

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#41]
Automatically adjust the layout to accommodate resizing the terminal

**Comment by ewodrich** [comment]
Tested in conjunction with case #42. 
Verified that resizing the --progress output window dynamically changes the visual layout, including re-aligning the worker boxes and the size of the scan results window. Also confirmed that the --progress output screen fails gracefully in the event the terminal resizes smaller than can accommodate the number of assigned workers along with the message "The current terminal size is inadequate for displaying progress output for the current scan options".
