### ISSUE TITLE
Gracefully handle terminals that are too small to output metrics for the requested number of workers

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#42]
When using the `--progress` option, it's possible that the number of workers may require more real estate than the current terminal size provides.

We could either:
- Show an error and gracefully exit
- Only show as many workers as will fit
- Implement some kind of scrolling and only show as many workers as will fit on screen at once

**Comment by akenion** [comment]
We will be showing an error and gracefully exiting for now. If we find there is demand for using the progress output with a large number of workers on small terminals, we will revisit the other options.

**Comment by ewodrich** [comment]
Verified the --progress output now fails gracefully in the event that the terminal is too small to display the requested number of workers, and continues to perform as expected when the terminal window is an adequate size. This includes the following: 

- various number of workers ranging from 1-8 completed as expected
- various numbers of workers ranging from 9-200 failed with the error message "The current terminal size is inadequate for displaying progress output for the current scan options"
- resizing the terminal window while a scan is running or once a scan completed fails with the error message above. 
- scanning without --progress continues to produce expected results
- additionally confirmed that the numbers with and without using the --progress option match between total files scanned and results found
- additionally confirmed the output is populating as expected with a large number of malware files found by scanning traditionally and with --progress option

**Comment by ewodrich** [comment]
New display error found. When selecting a number of workers that maximizes the terminal window size (see screenshot), the box for scan results is obscured and progress output ends abruptly with error message: `Error: 'LogBox' object has no attribute 'cursor_offset'`. 

Instead, allow only enough workers that will allow the results window to display in a minimum set size, and allow the progress output to fail with the error message "The current terminal size is inadequate for displaying progress output for the current scan options" as we do if the amount of workers does not fit on screen. 

<img width="1427" alt="image" src="https://github.com/wordfence/wordfence-cli/assets/104381949/aa2eba56-6489-4415-ab8b-00a8219ae835">

**Comment by ewodrich** [comment]
Tested with a variety of workers on both a laptop monitor and an external monitor. Verified workers and scan results screens display when able or else fail with the error message `The current terminal size is inadequate for displaying progress output for the current scan options`. Additionally retested the following: 

- resizing the screen to both too small for output to display (fails as intended) or to a size that repositions the workers on screen
- scanned small and large amounts of malware findings
- multiple scans performed with various options including defined output-path, various number of workers, stderr routed to error log, stdout, allow-io-errors, include-files-pattern, and chunk-size.
