### ISSUE TITLE
NocClient requests do not time out

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#50]
The `NocClient` constructor accepts a `timeout` parameter with a default value, but this is not currently passed to the underlying requests library when making requests and hence the requests will never time out.

**Comment by dallasmyers** [comment]
Verified that NocClient requests timeout after a short period of time. Testing proved the request to time out after about 90 seconds.

- checked by changing the the noc1 URL to use plain http and disabling the cache
- verified the request consistently timed out after about 90 seconds with these changes
- compared to previous version of CLI, and verified it was previously taking much longer - upwards of 6 minutes

**Comment by akenion** [comment]
Both the connect and read timeouts are actually set to 30 seconds. The connect timeout applies independently to each IP address returned by the DNS lookup. If you attempt to connect to a domain name that has 3 separate IP addresses assigned, it will allow up to 30 seconds to attempt to connect to each IP, resulting in a potential maximum timeout of 90 seconds in that example case.
