### ISSUE TITLE
Make IO error fatality configurable

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#52]
Currently when encountering file permission errors during a scan, the scanned files trigger a non-fatal error which could result in files being skipped without user's knowledge. For now, change to make IO errors fatal. 

Future considerations: add a second window in the --progress output to capture errors if we want to allow the scan to continue. Alternatively consider adding a flag to skip or fail in the event of encountering errors during a scan.

**Comment by akenion** [comment]
We're going to proceed with adding a `--allow-io-errors` flag. By default, IO errors will be fatal, but if this flag is set a warning will be issued instead and unreadable paths will just be skipped.

**Comment by akenion** [comment]
We're making one additional minor change in the scope of this issue related to logging errors. When stderr is not a TTY (i.e. if it's redirected to a file) and progress output is enabled, we're still going to write log output to `stderr`. Right now it's only included in the progress output in that case so warnings like those from the `--allow-io-errors` flag would simply be lost.

**Comment by dallasmyers** [comment]
Verified that IO errors are fatal by default and with the `--allow-io-errors` flag enabled, they are treated as warnings and the unreadable paths are skipped.

- checked that the option is added under --help
- checked that IO errors by default are fatal and terminate a scan
- checked with the `--allow-io-errors` flag enabled, the same errors are treated as warnings and allow the scan to continue running. The errors are no longer fatal or terminate a scan.
- checked the flag enabled along with --progress
- checked both permission and directory errors
- checked the errors are logged correctly when output is redirected
