### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by thecommish3** [wordfence/wordfence-cli#60]
I've requested a license key, it's a 224-character string that came in an email from Wordfence.

Downloaded and verified the package for my server with no issues, but when trying to run configuration, and prompted for the license, I just get "License validation failed. Please try again.". I requested a second license key, fails also.

Is there something else that is supposed to be entered at this prompt?

**Comment by akenion** [comment]
You're correct that the 224-character string you received in the email is what should be entered when prompted for the license key.

License validation requires making an HTTP request to one of our API servers. Can you ensure that you system can reach `noc1.wordfence.com` via HTTPS? Assuming the license is being entered correctly, the validation failure is likely an issue communicating with the API.

What output do you get if you run the following on your server?
```
curl -v https://noc1.wordfence.com/v2.27/
```
