### ISSUE TITLE
Display notice when files are skipped

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#62]
When at least one file is not included in the scan, the log output should include a notice indicating the number of skipped files and how to include these files in a scan.

**Comment by akenion** [comment]
This notice should suggest using the new `--include-all-files` flag as specified in #63.

**Comment by dallasmyers** [comment]
Verified the changes are working as expected including the following:

1. New message is added when files are skipped during a scan that includes the number of skipped files and how to include them in the scan. Example message: `1424 file(s) were skipped as they did not match the configured include patterns. Use --include-all-files (or -a) to include all files in the scan.`
2. Scanning with `--include-all-files` (or `-a`) successfully includes the previously skipped files. Compared the number of files scanned with this option vs the number of files skipped + number of files scanned with default settings, to verify they both equal the same totals.
3. The message is included in both, stdout and the curses interface.
4. Additional testing completed that includes:
    - Scanning with a Free key
    - Scanning with a Premium key
    - Scanning with `--output-path` still redirects output as expected
