### ISSUE TITLE
Add flag to include all files in scan

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#63]
Add an `--include-all-files` flag that will cause all files in scanned directories to be scanned regardless of extension. This should be functionally equivalent to using `--include-files-pattern=".*"` in the current version.

**Comment by akenion** [comment]
Additionally, the help messaging should be updated to indicate that only files matching certain patterns are scanned by default.

**Comment by akenion** [comment]
The above PR also implements a shorthand `-a` flag as an alias for `--include-all-files`.

**Comment by ewodrich** [comment]
Verified the changes are working as expected including the following: 

1. new command `–-include-all-files` and `-a` displays in —help as expected, and that the help mentions "By default, only files matching certain extensions are scanned"
2. Scanning with `--include-all-files` works as expected, without error. Also compared the number of files scanned using this option vs the total number of files skipped + total number of files scanned with default settings equal the same totals. 
3. Scanning with `-a` works as expected, without error. Also compared the number of files scanned using this option vs the total number of files skipped + total number of files scanned with default settings equal the same totals. 
4. Additional testing completed with new options that includes
- with Free key
- with Premium key
- scanning recursive symlinks work as before (see note below)
- `-a` and `--include-all-files` produce the same number of files
- `--include-files-pattern=.*` produces same result as `-a`
- `--include-files` continues to work as intended
- `--exclude-files` continues to work as intended
- using `-a` in combination with `--exclude-files-pattern` or `--exclude-files` works as anticipated by scanning all files except those defined to be excluded
- results route to `--output-path`

While testing this case, opened Case #74 for a new finding when scanning a directory with a symlink pointing above the target directory either producing an error or placing the scan into a loop.
