### ISSUE TITLE
Add a subcommand of "configure" for configuring Wordfence CLI, replacing the --configure option

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#72]
### **New Installations:** 
Add a new `configure` subcommand for users to walk through configuring Wordfence CLI both upon installation and when wanting to setup a new configuration. This will replace the current` --configure` option. 

The expected user flow is: 

1. Install Wordfence CLI using pip or other installation methods
2. Run `wordfence configure` which steps the user through configuring the wordfence-cli.ini file with the standard options including:
    -requesting a free key or, if "no" is selected, inputting a paid license key
    -accepting license terms (skipped if inputting a paid key)
    -setting default cache directory
    -allowing additional workers to be set (default of 1)
3. Wordfence CLI is ready to use!

### **When attempting any `wordfence` command before configuring Wordfence CLI** 
In the event a user attempts any `wordfence` command without having a working wordfence-cli.ini file, they will be prompted to first complete the configuration. This includes any command that initiates wordfence cli such as: 

-   wordfence
-   wordfence vuln-scan [with or without directory path]
-   wordfence malware-scan [with or without directory path]
-   wordfence --help

Ex: User installed Wordfence CLI but has not yet configured it and attempts a command like the following: 
`$ wordfence vuln-scan /public_html `
You must configure Wordfence CLI before it can be used. Would you like to configure Wordfence CLI now? Y/n
-    if Y, run `wordfence configure`
-    if n, exit back to command line (default)

Upon completing the configure subcommand, alert the user of the following (or a similar sentiment) and return the user to the command line: 
"Your Wordfence CLI license has successfully been configured. You may now access all of Wordfence CLI's commands. "

In the event of a user inputting `wordfence —-help` or simply `wordfence`, display the --help options followed by configuration prompt as mentioned above with: 
"You must configure Wordfence CLI before it can be used. Would you like to configure Wordfence CLI now? Y/n
-    if Y, run `wordfence configure`
-    if n, exit back to command line (default)

### **Converting current users to new configuration**
For this release we also need to convert existing wordfence-cli.ini files for current users to the new format that includes a [DEFAULT] global option,  [MALWARE-SCAN] (formerly [SCAN]), and [VULN-SCAN] options. 

After the user installs/upgrades to version 2.0.1, they will likely next run a wordfence cli command. When any command is input, the user should be prompted to update their configuration. The expected flow is: 

1. User updates wordfence CLI to latest version and has an existing wordfence-cli.ini file from prior to WF-CLI 2.0.1
2. User runs any `wordfence` command,
3. Prompt user with "A configuration file for an older version of Wordfence CLI was detected; would you like to update it now?" Y/n 
4. If n return user to command line. They will not be able to run wordfence CLI without having the new configuration in place. 
5. If "Y", prompt user to follow the prompts to update values and hit enter to keep existing values unless otherwise prompted. First showing the current option setting and then provide opportunity to change the current setting. 
For example: 
```
Current license: abcdefgdc4de91f7407da2c0ed4eafb1e160d91b4646d5a8f50f0b1901828d81
Would you like to automatically request a free Wordfence CLI license? [y/n] (default: n):n
Cache directory (current: ~/.cache/wordfence): [user defines or hits enter to skip]
Number of worker processes (8 CPUs available) (current: 4): [user defines or hits enter to skip]
Would you like to keep any custom settings? [Y/n] (default: Y)
```
6. Update the wordfence-cli.ini file with the new formats that includes:
- a global [DEFAULT] section with license key, cache setting, any other user defined settings that don't specifically apply to another option
- a [MALWARE-SCAN] section with number of workers and any other user defined settings that specifically apply to [MALWARE-SCAN]
- A [VULN-SCAN] section

### **Overwriting existing configuration file**
This is in the event the user already has a currently configured wordfence-cli.ini file. If not, refer to "Converting current users to new configuration" above. 
If a wordfence-cli.ini file already exists and the user inputs `wordfence configure` prompt them with:
"An existing configuration file was found at [path]/wordfence-cli.ini, do you want to overwrite it? [y/n] (default: n):"

- If "Y" take through the configuration setup like a new installation above. 
- If "n", return user to command line and make no changes to the wordfence-cli.ini file.

**Comment by akenion** [comment]
The piece about converting existing config files has been broken out as #76 due to a dependency on #75.

**Comment by akenion** [comment]
In the scope of this, a `help` subcommand has been added as well.

**Comment by ewodrich** [comment]
Verified the new `wordfence configure` subcommand is working as expected in the following scenarios: 
- a new install with `wordfence configure`
- new install with `wordfence malware-scan`
- new install with `wordfence vuln-scan`
- overwriting ini files with an existing install when using `wordfence configure`

In summary, the configure subcommand whether explicitly stated or in the event the user attempts a scan without having an existing configuration (ini file) in place, is prompting the user to use a free license, or if n, to input a license. If the user requests an automatic free license they are then prompted to accept license terms. In all cases for new configurations the user is then prompted to choose a cache directory, and number of workers. In the event the configure subcommand has been invoked while a configuration file is in place the user is additionally prompted to see if they want to keep their existing settings for license key, cache directory and workers. Any custom settings from the original configuration file are retained with the updated file. 

Note that change to the original specifications are that `wordfence help` and `wordfence version` (both new subcommands) do not prompt the user to configure wordfence CLI which was a decision made after the original specifications.
