### ISSUE TITLE
Improve messaging in the case of invalid regex input 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#73]
Currently if an invalid regex is input, an error message of `Error: nothing to repeat at position 0` is returned, noted when using both --include-files-pattern and --exclude-files-pattern.  

Example: 
`wordfence scan . --include-files-pattern=*.txt `
returns
`Error: nothing to repeat at position 0`

Change the message to the following, specifying the invalid parameters input by the user for <invalid-pattern>:
`Invalid pattern specified: <invalid-pattern>`

**Comment by dallasmyers** [comment]
Verified the changes are working as expected including the following:

1. The message has been improved for invalid regex input. It now specifies that the “pattern must be a Python regex” and what was received that was invalid.
2. Check message for `--include-file-patterns`, or` -N`: `Error: File inclusion pattern must be a Python regex, received: "*.txt"`
3. Check message for `--exclude-file-patterns`, or `-X`: `Error: File exclusion pattern must be a Python regex, received: "*.txt"`
4. Attempted various invalid file patterns and verified the `received: "<invalid pattern>"` part of the message reflects correctly
5. Check that valid file patterns work as expected and the scan is successful
6. Checked with other options included, such as `--debug`, and verified the output
