### ISSUE TITLE
Rename `scan` command to `malware-scan`

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#75]
With the addition of the `vuln-scan` command in #64, it is no longer apparent that the existing `scan` command solely scans for malware and not vulnerabilities. It should be renamed to `malware-scan` to avoid any ambiguity.

Additionally, if `scan` is invoked after this change, it should inform the user that the `scan` command has been renamed.

**Comment by ewodrich** [comment]
Verified the message _"The "scan" subcommand has been renamed to "malware-scan" "_  is returned when the command `wordfence scan` is invoked. Repeat tested somewhat at random with a variety of available malware-scan options. General testing of the `malware-scan` command is in progress to verify the options with the new command name are continuing to work as expected. 

One issue was found with the option `wordfence scan --help` or -h where it returned the following, however this is to be addressed in Case #85 .
```
usage: scan [-h]
options:
  -h, --help  show this help message and exit
```
