### ISSUE TITLE
Add `version` subcommand

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#78]
This will result in the same output as the existing `--version` flag.

**Comment by dallasmyers** [comment]
Verified the changes are working as expected including the following:

1. The `version` subcommand has been added. Verified it results in the same output as the existing `--version` flag.
2. Checked that `version` works as expected with other options, such as `--help`, `--no-banner`, etc.
3. Checked that the existing `--version` flag still works as expected with the wordfence command and subcommands
