### ISSUE TITLE
Improve malware-scan output

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#88]
- Change "matching" to "suspicious"
- Automatically scale units (bytes, KB, MB, etc.) based on value

**Comment by dallasmyers** [comment]
Verified the changes are working as expected including the following:
1. Check that malware-scan output now reads “Found [number] suspicious file(s) . . .”. 
    Example message: `Found 1 suspicious file(s) after processing 2300 file(s) containing 52.1 MiB over 109 second(s)`
3. Check both, `stdout` and the curses interface using `--progress`
4. Check that `malware-scan` output now scales units based on value
5. Check that various values appear correctly, such as B, KiB, MiB, etc.
6. Additional testing completed that includes:
    - Check that `--output-path` still redirects and the output messaging still appears correctly when using this option.
    - Check output with a free key
    - Check output with a premium key
