### ISSUE TITLE
Support multiple tiers of config files

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#89]
- Read from a global `/etc/wordfence/wordfence-cli.ini` file first, if present
- Overwrite global configuration with values from `~/.config/wordfence/wordfence-cli.ini`, if present

**Comment by ewodrich** [comment]
Verified a global config is working in the following scenarios: 

- License and cache from global config recognized when no license exists in local config. 
- removing local .ini file is working when global .ini file exists with just a license
- empty global and empty local .ini prompts for license as expected
- empty global and configured local .ini is working as expected without error
- free license in local .ini is overriding the global premium license configuration
